node(label: 'label-a') {

        deleteDir()

        stage('checkout') {
           
           echo "Hello World!!!"
        }

        stage('build') {
            println('Building.....')
            echo "Build"
        }
}

