//node(label: 'label-a') {
    // node('label-a') {  //This will not work
    node('label-c') {  //This will not work

        deleteDir()

        stage('checkout') {
           
           echo "Hello World!!!"
        }

        stage('build') {
            println('Building.....')
            echo "Build"
        }
}

