pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
               sh 'echo "HEllo Build Stage"'
            }
        }
        stage('Test') { 
            steps {
                sh 'echo "HEllo Test Stage"'
                // 
            }
        }
        stage('Deploy') { 
            steps {
                sh 'echo "HEllo Deploy Stage"'
                // 
            }
        }
    }
}