pipeline { 
    agent { label 'DONOTUSE' } 
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') { 
            steps { 
                sh 'echo "Hello Build Stage"' 
            }
        }
        stage('Test'){
            steps {
                sh 'echo "Hello Test Stage"'
    
            }
        }
        stage('Deploy') {
            steps {
                
                sh 'echo "Hello Deploy Stage"'
            }
        }
    }
}